version: 3.8'

services:
  postgres:
    build: ./src/database
    networks:
      - task6
    container_name: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  node:
    build: .
    networks:
      - task6
    container_name: node

    restart: always
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}

networks:
  task6:
    driver: bridge